{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "apiclarity.name" . }}-postgresql
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
spec:
  serviceName: {{ include "apiclarity.name" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "apiclarity.name" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "apiclarity.name" . }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: '{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}'
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: postgres-password
          ports:
            - name: postgresql
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
  {{- if .Values.postgresql.primary.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresql.primary.persistence.size }}
  {{- end }}
{{- end }}
